// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpizUuzt-JGEns-VyzaRtwJhStLSiwLg0',
    appId: '1:592079991489:web:d6f83a983375af967b1a40',
    messagingSenderId: '592079991489',
    projectId: 'swifthome0011',
    authDomain: 'swifthome0011.firebaseapp.com',
    storageBucket: 'swifthome0011.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNnrfpzS_-BJtmvA-C1GhV-CwzNAucgvM',
    appId: '1:592079991489:android:2fbe7fe00b77500d7b1a40',
    messagingSenderId: '592079991489',
    projectId: 'swifthome0011',
    storageBucket: 'swifthome0011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4m0xxlolhiziXQNHCZj9Z4Td4lpQQ3bs',
    appId: '1:592079991489:ios:5e41848aeeaa5d5c7b1a40',
    messagingSenderId: '592079991489',
    projectId: 'swifthome0011',
    storageBucket: 'swifthome0011.appspot.com',
    iosBundleId: 'com.example.swifthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4m0xxlolhiziXQNHCZj9Z4Td4lpQQ3bs',
    appId: '1:592079991489:ios:5e41848aeeaa5d5c7b1a40',
    messagingSenderId: '592079991489',
    projectId: 'swifthome0011',
    storageBucket: 'swifthome0011.appspot.com',
    iosBundleId: 'com.example.swifthome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpizUuzt-JGEns-VyzaRtwJhStLSiwLg0',
    appId: '1:592079991489:web:83cee329571c0ca67b1a40',
    messagingSenderId: '592079991489',
    projectId: 'swifthome0011',
    authDomain: 'swifthome0011.firebaseapp.com',
    storageBucket: 'swifthome0011.appspot.com',
  );
}
